### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Teages** [Teages/vTablet#7]
- [ ] new api 
- [ ] stylus button support (server side only)
- [ ] document

## Client

- [ ] code clean
- [ ] custom background
- [ ] auto hide delay compoment
- [ ] better aria setting
- [ ] google play
- [ ] update about

## Server

- [ ] i18n
- [ ] update check
- [ ] qrcode
